Highlight incompatibilitiy with Adafruit ecosystem
adafruit/circuitpython-org pull request #1114
Opened 2022-12-12 22:06 UTC by dglaude

I try to manage expectation about this board and avoid short circuit or broken sensor. 1) I almost burned myself by mixing LOLIN I2C JST SH accessories and Adafruit QTPy, reverse way, I could have destroyed an Adafruit sensor by connecting it to Lolin S2 Pico. 2) The screen does not work as expected for a build-in screen, DISPLAY is not defined when you `import board`

I did hesitate between making a special section like "Caveats" or highlighting how it deviate from one can expect from a board running CircuitPython.

2022-12-12 22:16 UTC, deshipu commented
I suppose the display initialization could be added to board.c for this board?

2022-12-13 15:35 UTC, dglaude commented
Hi @deshipu , yes there must be a way to have the screen work as expected but apparently it is the first board where the screen is connected in I2C so there was no example to copy from.
https://github.com/adafruit/circuitpython/issues/7325#issuecomment-1345048637

If this PR make's it, and then later someone implement that the proper way, we can remove the warning (or say starting with CP9.0.0-alpha1 this statement is not true anymore).

2022-12-16 07:22 UTC, evildave666 commented
To be fair, the S2 Pico circuitpython-org entry (I wrote it) does have a mention that the connector is not Stemma-QT pinout.

2022-12-19 15:27 UTC, dhalbert requested changes
Thanks! One suggestion for increased clarity.

2022-12-19 15:27 UTC, dhalbert commented on _board/lolin_s3.md
> +  - Lolin I2C JST SH 4-pin port (**not QWIIC/Stemma-Qt pinout**) using `GPIO42` (SDA) and `GPIO41` (SCL)
```suggestion
  - Lolin I2C JST SH 4-pin port (**does not match QWIIC/Stemma-Qt pinout**) using `GPIO42` (SDA) and `GPIO41` (SCL)
```

2022-12-29 00:09 UTC, dglaude commented
There might be a problem with the CI and Jekyll in particular, not sure why those simple change break it.

2022-12-30 00:21 UTC, jepler approved these changes
Approving based on Dan's previous review

2022-12-30 00:22 UTC, merged