Generate absolute URLs automatically
adafruit/circuitpython-org pull request #1378
Opened 2024-03-30 01:26 UTC by jepler

This allows a `localhost:4000`-style URL to be generated for local testing, but still gives an absolute URL, which enhances compatibility with RSS readers. A comment is added explaining the reason for the absolute URL.

Closes #1374

2024-03-30 01:32 UTC, dhalbert requested changes
This now has merge conflicts due to merging #1375. But I am confused too: where does `absolute_url` come from?

2024-03-30 01:36 UTC, dhalbert approved these changes
OK, I see `absolute_url` is predefined, apparently. I'll approve this. Could you merge when you are ready to check the result immediately? Thanks.

2024-03-30 01:40 UTC, jepler commented
absolute_url: https://jekyllrb.com/docs/liquid/filters/#absolute-url

let's do this now if you're able

2024-03-30 01:41 UTC, merged

2024-03-30 01:43 UTC, jepler commented
generation looks good
```html
  <!-- (uses an absolute URL for better compatibility with RSS readers -->
  <img srcset="https://circuitpython.org/assets/images/boards/small/raspberry_pi_pico.jpg 300w,
               https://circuitpython.org/assets/images/boards/large/raspberry_pi_pico.jpg 700w" sizes="(max-width: 1024px) 700px,
              300px" src="/assets/images/boards/large/raspberry_pi_pico.jpg" alt="Image of Board" loading="lazy">

            ```

2024-03-30 01:44 UTC, jepler commented
hmm I lost the | absolute_url on the src=, oops

2024-04-01 15:30 UTC, makermelissa commented
> hmm I lost the | absolute_url on the src=, oops

You may need to point https://github.com/adafruit/circuitpython-org/blob/main/feed.html#L20 to board_image.html rather than feed_board_image.html.