Update m5stack_dial.md with Adafruit purchase link
adafruit/circuitpython-org pull request #1425
Opened 2024-06-13 21:14 UTC by RetiredWizard

The Adafruit project page should probably also be updated to indicate that there is CircuitPython support but I don't know how to make that update.

2024-06-13 22:47 UTC, makermelissa commented
> The Adafruit project page should probably also be updated to indicate that there is CircuitPython support but I don't know how to make that update.

Add the product URL under board_url:

2024-06-13 23:12 UTC, RetiredWizard commented
Sorry @makermelissa, I thought I was being clever and skipped re-reading the instructions. Hopefully this is what you need 😁

2024-06-14 16:17 UTC, makermelissa commented
Can you please leave both URLs? It's a list, so it can have multiple URLs like this:
```
board_url:
  - "url1"
  - "url2"
 ```

2024-06-14 16:21 UTC, makermelissa requested changes
By having both, we can use the data in other ways in the future.

2024-06-14 16:21 UTC, makermelissa commented on _board/m5stack_dial.md
> + - "https://www.adafruit.com/product/5966"
```suggestion
 - "https://docs.m5stack.com/en/core/M5Dial"
 - "https://www.adafruit.com/product/5966"
```

2024-06-14 17:29 UTC, makermelissa approved these changes
Thank you. Looks great.

2024-06-14 17:29 UTC, merged