Add latest round of missing boards
adafruit/circuitpython-org pull request #1436
Opened 2024-07-22 16:42 UTC by makermelissa

This adds CircuitPython missing boards and Blinka missing boards.

2024-07-22 20:28 UTC, tannewt requested changes
One weird filename. Looks good otherwise. Thanks for adding these!

2024-07-22 20:28 UTC, tannewt commented on _board/unexpectedmaker_feathers2_neo copy.md
I suspect this file needs to be renamed so it doesn't include `copy`.

2024-07-22 20:46 UTC, makermelissa commented on _board/unexpectedmaker_feathers2_neo copy.md
Nice catch. I'll take a closer look.

2024-07-22 20:48 UTC, makermelissa commented on _board/unexpectedmaker_feathers2_neo copy.md
Fixed.

2024-07-23 00:34 UTC, dhalbert approved these changes

2024-07-23 00:35 UTC, merged