Update trinket_m0_haxpress.md
adafruit/circuitpython-org pull request #1506
Opened 2024-10-21 22:59 UTC by Timeline8

Links are now all dead links.

2024-10-22 13:58 UTC, FoamyGuy requested changes
There is an archived version available here: https://web.archive.org/web/20210727135908/http://daveastels.com/trinket-m0-express-hack.html It's missing some of the original images, but it's got a lot of information for anyone who would want to create one of these. 

I think it'd be good to link to that one and note it in the text as an archived version.

2024-10-23 00:06 UTC, Timeline8 commented
Updated changes with new archived URL. Not sure if I did it right for the Board URL line though.

2024-10-23 00:07 UTC, Timeline8 reviewed
Updated links to use the archived version of the old web page no longer online.

2024-10-23 13:13 UTC, FoamyGuy commented on _board/trinket_m0_haxpress.md
> +board_url: https://web.archive.org/web/20210727135908/http://daveastels.com/trinket-m0-express-hack.html
I think it's best to make formatting match all of the other device config files with the board URL on it's own line with a hyphen at the beginning.
```
 - "https://web.archive.org/web/20210727135908/http://daveastels.com/trinket-m0-express-hack.html"
```

I'm not entirely certain if that syntax is 100% necessary, and I also don't know for sure where this board_url value gets used, but I think keeping it consistent across devices whenever possible is best.

2024-10-23 18:56 UTC, Timeline8 reviewed
Agreed. Looks good to me.

2024-10-23 19:01 UTC, Timeline8 reviewed
OK I think it looks good now.

2024-10-23 19:32 UTC, FoamyGuy approved these changes
Thank you!

2024-10-23 19:32 UTC, merged