Add new board Bast Wifi
adafruit/circuitpython-org pull request #561
Opened 2020-10-13 20:46 UTC by Soulkrown

Add new board Bast Wifi

2020-10-13 21:07 UTC, makermelissa requested changes

2020-10-13 21:07 UTC, makermelissa commented on _board/bast_wifi.md
> +name: "bast_wifi"
Could you change the name and title from `bast_wifi` to `Bast WiFi` since that's how it will appear on the website.

2020-10-13 21:07 UTC, makermelissa commented on _board/bast_wifi.md
> +features:
Under features, you could add WiFi and anything else from the list at https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website/adding-to-downloads

2020-10-13 21:28 UTC, Soulkrown commented
Hi @makermelissa 
 I already made the changes in the points that you asked me. Thank you very much for you review

2020-10-13 21:46 UTC, makermelissa approved these changes
Looks great! Thanks for submitting this and making the requested changes.

2020-10-13 21:46 UTC, merged

2020-10-14 15:23 UTC, Soulkrown commented
Hi @makermelissa
I am having a problem trying to download the uf2 file from the card as the download button does not appear, how can I fix the problem? the location of the card is [](https://github.com/adafruit/circuitpython/tree/main/ports/esp32s2/boards/electroniccats_bastwifi)
Thank you for your attention.
Have a nice day

2020-10-14 15:30 UTC, makermelissa commented
It looks like the official board name in circuitpython is `electroniccats_bastwifi`. I just submitted #562 to remove the old file and rename this one to the correct name. This should fix the issue.