Add more Blinka Info with photos swapped
adafruit/circuitpython-org pull request #614
Opened 2021-01-08 18:01 UTC by makermelissa

This PR supersedes #577.

2021-01-09 01:15 UTC, makermelissa commented
@ptorrone fyi, this is just waiting on a review, but is otherwise complete.

2021-01-11 15:58 UTC, kattni requested changes
@makermelissa Thank you for adding this! Potential suggestion below. If you'd rather not, let me know and I'll approve this.

2021-01-11 15:58 UTC, kattni commented on blinka.html
> +    Blinka brings CircuitPython APIs and, therefore, libraries to single board computers (SBCs). It is a <a href="https://pypi.org/project/Adafruit-Blinka/">pip installable Python library</a> that ru
Consider including `CircuitPython` before libraries. I had to read the sentence a couple of times, and that would clarify things. Including "CircuitPython" in the later "Libraries" sentence might make sense as well. Up to you though! 
```suggestion
    Blinka brings CircuitPython APIs and, therefore, CircuitPython libraries to single board computers (SBCs). It is a <a href="https://pypi.org/project/Adafruit-Blinka/">pip installable Python library</a> that runs in normal "desktop" Python. The CircuitPython runtime isn't used. <a href="https://pypi.org/search/?q=adafruit-circuitpython">CircuitPython libraries</a> can also be installed via pip. See <a href="https://learn.adafruit.com/circuitpython-on-raspberrypi-linux"> the guide</a> for further details.
```

2021-01-11 16:00 UTC, makermelissa commented
Thanks @kattni, it sounds good to me.

2021-01-11 16:01 UTC, kattni approved these changes

2021-01-11 16:01 UTC, merged