Format as code
adafruit/circuitpython-org pull request #860
Opened 2022-02-01 13:02 UTC by fabaff

2022-02-01 16:00 UTC, makermelissa requested changes

2022-02-01 16:00 UTC, makermelissa commented on _board/muselab_nanoesp32_s2_wrover.md
> +``
Should there be 3 backticks here to close out the code block?

2022-02-15 16:09 UTC, closed without merging

2022-02-15 16:48 UTC, fabaff commented
Sorry for the duplicate.

2022-02-15 17:06 UTC, makermelissa commented
No worries, You can simply update and push changes to any existing ones in the future and everything updates.