Seeed Studio is making a naming change on the XIAO serie
adafruit/circuitpython-org pull request #987
Opened 2022-07-07 21:17 UTC by dglaude

Seeed Studio is making a naming change on the XIAO serie of board, so I adapted 3 boards (skipping "Seeeduino XIAO - Keyboard Optimized")

https://www.seeedstudio.com/blog/2022/07/06/notice-on-product-name-change/

2022-07-07 22:27 UTC, Neradoc commented
Makes sense to me, maybe add something like "(Formerly Seeeduino Xiao)" for search purposes ?

2022-07-07 22:41 UTC, makermelissa commented
Would you like to updated the Manufacturer to "Seeed Studio" as well?

2022-07-26 15:15 UTC, makermelissa requested changes
Waiting on response to Neradoc's and my questions...

2022-08-01 22:34 UTC, ladyada commented
@dglaude please check the questions above

2022-08-14 12:14 UTC, dglaude commented
> Seeed Studio

If `SEEED` was their old name and `Seeed Studio` the new name, so yes that make sense.
But I don't know how to do that (it is used in the filter) and it also affect the Wio Terminal, so 5 boards in total.

PS:
I am not working for SEEED/Seeed Studio. Maybe those that contribued those board in the first place can propose a fix. :-)
This can be a separate PR, I only noticed the XIAO naming issue and that is what I tried to fix here.

2022-08-15 16:26 UTC, makermelissa commented
Hi, no worries. I wasn't assuming you worked for them. 

To change the name, just find the boards: https://circuitpython.org/downloads?manufacturers=SEEED (and it looks like you already located them), then in the board file, change manufacturer to "Seeed Studio". As long as you update all of the boards and they have the exact same spelling, the filter will update automatically (otherwise there will be a filter for every variation).

2022-08-15 18:06 UTC, dglaude commented
> change manufacturer to "Seeed Studio"

Hi @makermelissa I changed the 5 boards.

If that company want to improve those descriptions further or submit more board (I am pretty sure they have some more), I suggest to let them do it. I don't want me nor you to do that work for them. ;-)

2022-08-15 18:09 UTC, makermelissa approved these changes
Looks good. Thank you.

2022-08-15 18:09 UTC, merged